# Build configuration for https://cirrus-ci.org

freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  install_script:
    - pkg install -y autoconf automake libtool pkgconf python pcre2 dejagnu libxml2 texinfo
  build_script:
    - sh ./autogen.sh
    - CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure
    - make
  test_script:
    - make check
    - make distcheck
